# Generated by Django 3.1.5 on 2021-07-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followee_id',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
