# Generated by Django 3.1.5 on 2021-07-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_auto_20210702_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
