# Generated by Django 3.1.5 on 2021-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_auto_20210702_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
