# Generated by Django 3.1.5 on 2021-08-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_customuser_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
