# Generated by Django 3.1.5 on 2021-08-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_auto_20210822_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followee')},
        ),
    ]
