# Generated by Django 3.1.5 on 2021-04-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('cocktails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquoramount',
            name='liquor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquors.liquor'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cocktails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='liquors',
            field=models.ManyToManyField(to='liquors.Liquor'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='saved_by',
            field=models.ManyToManyField(default=None, related_name='saved_cocktails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='viewed_by',
            field=models.ManyToManyField(default=None, related_name='viewed_cocktails', to=settings.AUTH_USER_MODEL),
        ),
    ]
