# Generated by Django 3.1.5 on 2021-01-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0003_auto_20210118_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="image",
            field=models.ImageField(default="./defaultimg.png", upload_to=""),
        ),
    ]
