# Generated by Django 3.1.5 on 2021-01-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_cocktail_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
    ]
