# Generated by Django 3.1.5 on 2021-01-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0001_initial'),
        ('cocktails', '0007_cocktail_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='liquors',
            field=models.ManyToManyField(to='liquors.Liquor'),
        ),
    ]
