# Generated by Django 3.1.5 on 2021-01-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_cocktail_liquors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='instructions',
            field=models.TextField(default='', verbose_name='Instructions'),
        ),
    ]
