# Generated by Django 3.1.5 on 2021-02-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0010_auto_20210125_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="amt_saved",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
