# Generated by Django 3.1.5 on 2021-03-03 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0013_auto_20210303_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
