# Generated by Django 3.1.5 on 2021-03-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0014_auto_20210303_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='uuid',
            new_name='public_id',
        ),
    ]
