# Generated by Django 3.1.5 on 2021-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0017_auto_20210313_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
