# Generated by Django 3.1.5 on 2021-03-17 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktails', '0019_auto_20210314_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='viewed_by',
            field=models.ManyToManyField(default=None, related_name='viewed_cocktails', to=settings.AUTH_USER_MODEL),
        ),
    ]
