# Generated by Django 3.1.5 on 2021-03-03 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0004_auto_20210303_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
