# Generated by Django 3.1.5 on 2021-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_reset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='verification_code',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
