# Generated by Django 3.1.5 on 2021-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_pictures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepicture",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
