# Generated by Django 3.1.5 on 2021-03-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20210223_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_cocktails',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='saved_cocktails',
        ),
    ]
