# Generated by Django 3.1.5 on 2021-01-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0002_cocktails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cocktail",
            old_name="complexty",
            new_name="complexity",
        ),
    ]
