# Generated by Django 3.1.5 on 2021-01-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
        ("cocktails", "0004_cocktail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(to="ingredients.Ingredient"),
        ),
    ]
