# Generated by Django 3.1.5 on 2021-01-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0009_cocktail_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="instructions",
            field=models.TextField(default="mix together", verbose_name="Instructions"),
        ),
    ]
