# Generated by Django 3.1.5 on 2021-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0011_auto_20210223_0013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="amt_saved",
            field=models.PositiveIntegerField(),
        ),
    ]
