# Generated by Django 3.1.5 on 2021-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0015_auto_20210303_0104"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
