# Generated by Django 3.1.5 on 2021-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0016_cocktail_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
    ]
