# Generated by Django 3.1.5 on 2021-03-17 03:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("liquors", "0005_auto_20210303_0123"),
        ("ingredients", "0005_auto_20210303_0123"),
        ("cocktails", "0020_cocktail_viewed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="amt_saved",
        ),
        migrations.CreateModel(
            name="LiquorAmount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.cocktail",
                    ),
                ),
                (
                    "liquor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="liquors.liquor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientAmount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cocktails.cocktail",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingredients.ingredient",
                    ),
                ),
            ],
        ),
    ]
