# Generated by Django 3.1.5 on 2021-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0021_auto_20210317_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(default='oz', max_length=10, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='liquoramount',
            name='unit',
            field=models.CharField(default='oz', max_length=10, verbose_name='Unit'),
        ),
    ]
