# Generated by Django 3.1.5 on 2021-03-26 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cocktails", "0022_auto_20210326_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cocktails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
