# Generated by Django 3.1.5 on 2021-04-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0023_auto_20210326_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='image',
        ),
    ]
