# Generated by Django 3.1.5 on 2021-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0025_auto_20210624_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
