# Generated by Django 3.1.5 on 2021-04-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocktails', '0001_initial'),
        ('cocktail_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailimage',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_image', to='cocktails.cocktail'),
        ),
    ]
