# Generated by Django 3.1.5 on 2021-07-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktails', '0025_auto_20210624_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=240, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cocktail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails.cocktail')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
