# Generated by Django 3.1.5 on 2021-07-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
