# Generated by Django 3.1.5 on 2021-04-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0024_remove_cocktail_image'),
        ('cocktail_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailimage',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_image', to='cocktails.cocktail'),
        ),
    ]
