# Generated by Django 3.1.5 on 2021-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
