# Generated by Django 3.1.5 on 2021-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
